### ISSUE TITLE
Never is not a functional language

### ISSUE THREAD

**Issue by gingerBill** [never-lang/never#19]
This is not a functional language as variables can be mutated.

**Comment by catb0t** [comment]
It's a C-style language compiled in the C runtime (with no huge special memory runtime of its own) that allows explicit loops and such things, which could be translated by Never into an immutable recursion -- except not in the C runtime, which will inevitably overflow the call or local stack at some point (thank you, L1 cache).

In lieu of such a large Haskell-class undertaking some simple concessions have to be made to the host Harvard architecture that the assembler and C compiler try to closely match.

Re-implement Never for a modern Lisp OS or something and you can probably get what you want because their `ld.so` is not like mine.

---

And to intentionally miss the point, the apparent mutability of variables could be implemented by underlying immutability, so that you may count `i` in a loop but in fact every time the value of `i` is copied and moved instead of being overwritten in-place.

I know you want mathematical purity from `let` (and perhaps `let const` or `let mut` should be added) but at some level there is a question of the *point*: is it to improve correctness, or to improve the *appearance* of correctness?

**Comment by gingerBill** [comment]
You are using a very loose definition of functional for your language, if not outright wrong.

```
And to intentionally miss the point, the apparent mutability of variables could be implemented by underlying immutability, so that you may count i in a loop but in fact every time the value of i is copied and moved instead of being overwritten in-place.
```
The underlying machine doesn't matter. A high level programming language (above assembly) is an abstraction for the programmer to use. The type system of the programming language itself determines whether the language is declarative/imperative or functional/logical/etc. 

The Never language seems more imperative than declarative which would mean it is not even the same classification of functional languages.

```
It appears mutable but has the semantics of being immutable with the obvious exception of breaking one-value-per-name in your code.
```
Then it is mutable. There are _multiple_ breaking "exceptions" which means that a named value (variable) can have its value changed through one means or another. This may happen on the actual machine (there are only a limited number of registers and memory) however, your abstraction (the programming language's type system) is the focus.

```
I know you want mathematical purity from let (and perhaps let const or let mut should be added) but at some level there is a question of the point: is it to improve correctness, or to improve the appearance of correctness?
```
I never said I wanted purity, rather to be classed as a functional language, the aspect of discussion would void it from being a functional language. 

---

To be clear, I am not commenting on the quality of the language rather the false advertisement.

**Comment by smaludzi** [comment]
Thank you for these comments. What can/should I do about them?

S.

**Comment by gingerBill** [comment]
I do love new interesting languages and _Never_ does look very interesting and has a lot of promise!

My recommendation is only to remove the term "functional" from the description. That is it.

**Comment by catb0t** [comment]
Personally I think one of `let mut` / `let const` is a good idea for the future, like Rust and F# which have explicit mutability for convenience.

Of course `let mut` requires more code changes to implement than explicit `let const` (where mutability is default), but IMO this is the simple way to still call it functional.

**Comment by bpunsky** [comment]
Functional-by-default. Not a bad way to structure a scripting language, especially since Never is very readable for a functional language in my opinion.

**Comment by smaludzi** [comment]
I think functional languages are those which evaluate expressions. Those which don't have side effects are additionally called pure. Since intruduction of assignments I removed pure adjective from Never classification. Because of that I will still call it functional.

I admit var and let keywords need more work. Thanks for information regarding let mut and let const.

**Comment by bogen85** [comment]
let const? too verbose... (IMHO)
let mut?   would not mut or var suffice?
(Yeah, I know this issue is closed)

**Comment by smaludzi** [comment]
I am trying not to submit not coherent code or ideas but this slipped. Now it back fired and I am looking for elegant solution to define mutables and constants. Maybe when releasing major version (e.g. modules and 64bit int float) it will be good opportunity to fix let var keywords even at the cost of breaking backwards compatibility (as not many people relay on it yet ;)
